# Generated by Django 5.1.6 on 2025-02-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('commit_count', models.IntegerField(default=0)),
                ('pull_request_count', models.IntegerField(default=0)),
                ('merged_pull_request_count', models.IntegerField(default=0)),
                ('repos', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
